name: Test Docker No-custom Action 2

on: 
  workflow_dispatch:

jobs:
  docker-example:
    runs-on: ubuntu-20.04
    container:
      image: maes95/time-action:1.0.0
    steps:  
    - name: Run entry point
      run: ls -la /