name: Test Composite Action

on: 
  workflow_dispatch:

jobs:
  run-maven-test:
    runs-on: ubuntu-latest
    name: A job to run test
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: openjdk
    - name: Run Maven Action
      id: maven-gha
      uses: ./.github/actions/composite/
      with:
        package: false
        exclude: 'selenium'
    - name: Get project version
      run: |
        [[ ${{ steps.maven-gha.outputs.project-version }} == "0.1.0-SNAPSHOT" ]] && echo "Works" || ( echo "Fail" && exit 1 )