name: Test JS Action

on: 
  workflow_dispatch:

jobs:
  get-date-test:
    runs-on: ubuntu-20.04
    name: A job to get Date
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Run GetDate Action
      id: js-gha
      uses: ./.github/actions/js/
      with:
        offset: "+2"
    - name: Echo date
      run: echo  ${{ steps.js-gha.outputs.time }}