name: Test Docker Services

on: 
  workflow_dispatch:

jobs:
  docker-example:
    runs-on: ubuntu-20.04
    services:
      app:
        image: maes95/items:2.4.0
        ports:
           - 8080:8080
    steps:
      - name: Get items
        run: sleep 10 && curl http://localhost:8080/api/items/